### ISSUE TITLE
Automatic installation failing

### ISSUE THREAD

**Issue by Noitidart** [Kishanjvaghela/react-native-cardview#11]
Doing automatic installation is not working. After doing `react-native link` I am getting this error:

```
C:\Users\Mercurius\Documents\GitHub\bouncerapp_android\android\app\src\main\java\com\bouncerapp\MainApplication.j
ava:27: error: cannot find symbol
            new RNCardViewPackage()
                ^
  symbol: class RNCardViewPackage
2 errors
```

**Comment by Noitidart** [comment]
I had to go into `C:\Users\Mercurius\Documents\GitHub\bouncerapp_android\android\app\build.gradle` and add:

```
compile project(':react-native-cardview')
``

into the `dependencies` block, as mentioned in the manual installation instructions.

Weird I don't know why automatic didn't take care of this.

**Comment by Kishanjvaghela** [comment]
@Noitidart I have tested and it works. There are no updates for a long time so I am closing issue. If it occurs again, then please reopen with a detailed test case.

**Comment by Noitidart** [comment]
Understood, thank you sir!
