### ISSUE TITLE
Please update npm 

### ISSUE THREAD

**Issue by Noitidart** [Kishanjvaghela/react-native-cardview#16]
I am using RN 0.49.3 and react 16.0.0-beta.5 and I think PropTypes package has been deprecated. It is causing a red screen and errors out.

**Comment by Noitidart** [comment]
Oh nice its fixed on github, but the package on npm is not yet updated.

**Comment by githubdoramon** [comment]
Any news here? Getting the same problem

**Comment by Kishanjvaghela** [comment]
I am busy in other projects, I will fix this in next two days.

**Comment by Noitidart** [comment]
Thank you sir!

**Comment by pureblood** [comment]
Any update on this?

**Comment by Kishanjvaghela** [comment]
#13

**Comment by Kishanjvaghela** [comment]
Fixed in https://github.com/Kishanjvaghela/react-native-cardview/commit/bd69b288d9d2f1012463a732e0b0e129f55ec5fa
