### ISSUE TITLE
Animate shadow?

### ISSUE THREAD

**Issue by Noitidart** [Kishanjvaghela/react-native-cardview#19]
Is it possible to animate this shadow? This has been such an amazing module, can't thank you enough for it.

**Comment by Kishanjvaghela** [comment]
Whan kind of animation? Can you give some examples/reference?

**Comment by Noitidart** [comment]
Thank you very much @Kishanjvaghela for being so supportive as always. My hope was to use it with the `Animated` API, example:


Render:
```
const anim = new Animated.value(0)

....
render() {
    const interpolated = anim.interpolate({ inputRange:[0,1], outputRange:[0,10] });
    return<Animated.Card cardElevation={interpolated} cardMaxElevation={interpolated} />
}

....

Animated.timing(anim, { toValue:1, duration:300 }).start();

```


This is the typical way Animated API is used, for instance the `Blur` view from Expo:

https://docs.expo.io/versions/latest/sdk/blur-view.html

**Comment by Noitidart** [comment]
A user just implemented an animation, this might help, I'm not familiar with the native side of things, so I'm hoping this share helps you out :)

https://github.com/react-native-community/react-native-blur/issues/152#issuecomment-353714361

Diff of changes made - https://github.com/AlpacaDB/react-native-blur/compare/b415e7774e046bdccc351da8e56581534777266e...1f0303a5c66179e3f9c84c9bf306968a2d453f19

**Comment by Kishanjvaghela** [comment]
Use Animated as per suggested by @Noitidart
