### ISSUE TITLE
YOGANODE

### ISSUE THREAD

**Issue by jaysmoodge** [Kishanjvaghela/react-native-cardview#20]
Cant run ur library. im getting this error

Cannot add child that doesnt have a YogaNode to a parent w/o a measure function......

im doing something like this:

				      <CardView
       			 		cardElevation={4}
        				cardMaxElevation={4}
        				cornerRadius={5}>
				        <Text>{this.state.tmpUser}</Text>
				      </CardView>
                                      <View>some view</View>

can u explain further.?

**Comment by Kishanjvaghela** [comment]
I have fixed this issue. Please use v2.0.0 or more. If still not working then feel free to open again.
