### ISSUE TITLE
Text-alignment in CardView does not work

### ISSUE THREAD

**Issue by dharavp** [Kishanjvaghela/react-native-cardview#24]
## When I try to  put textview center of the cardview. It does not work.

**Below I have shared my code:**
```
<CardView
           cardElevation={3}
           cardMaxElevation={3}
           cornerRadius={3}
           style={{
            	height: 60,
            	justifyContent: 'center',
            	alignItems: 'center',
            	margin: 20,
            	backgroundColor: '#ffffff' }}>
            	<View 
            	style={{
            		flex: 1,
            		justifyContent: 'flex-end', //changed justifyContent value to center
            		backgroundColor: 'red'
            	}}>
                <Text 
                style={{
                color: '#000000',
                fontSize: 12,
                backgroundColor: 'pink',
                textAlign: 'center'
                 }}
                >
                Helloo</Text>
                </View>
            </CardView>
```

**Below I have shared screenshot of my output:**

When I gave justifyContent flex-end to the View,it shows below output.
![cardview-text-end](https://user-images.githubusercontent.com/26294736/36474761-837ebb50-171e-11e8-99ec-b8487f92dcf5.png)

When I gave justifyContent center to the View,it shows below output.
![cardview-flex-center](https://user-images.githubusercontent.com/26294736/36474771-8c5f56c6-171e-11e8-8da5-3d5fcc60e374.png)

**Comment by HyuArzani** [comment]
i think it's because on android the justifyContent center calculate elevation height too, so your end of parent view is in the bottom shadow, i think it is android limitation when calculating on elevation

**Comment by ayehia** [comment]
the same issue here

**Comment by Kishanjvaghela** [comment]
I am busy with company work.. so after long time still didnt get any time to support this repo.. by next week-end I will try to fix this,

**Comment by Kishanjvaghela** [comment]
I have fixed this issue. Please use v2.0.0

**Comment by Kishanjvaghela** [comment]
I used your code. please check [Example3.js](https://github.com/Kishanjvaghela/react-native-cardview/blob/master/example/Example3.js)

![image](https://user-images.githubusercontent.com/11232063/45997635-e1dfb600-c0d2-11e8-8c3a-f2a5d75b548e.png)
