### ISSUE TITLE
A problem occurred configuring project ':react-native-cardview'

### ISSUE THREAD

**Issue by tamajitchakraborty** [Kishanjvaghela/react-native-cardview#25]
> A problem occurred configuring project ':react-native-cardview'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-cardview'. Minimum required is 25.0.0

i think you need to upgrade your android dependency.

**Comment by Yousefjb** [comment]
+1

**Comment by Kishanjvaghela** [comment]
I have updated android version. please use v2.0.0
