### ISSUE TITLE
CardView on Android doesn't support flexbox layout

### ISSUE THREAD

**Issue by aranda-adapptor** [Kishanjvaghela/react-native-cardview#3]
Am I right in thinking this?

I'm trying this and all the text elements appear on top of each other on Android, but on iOS it works as expected:

```
          <CardView
            style={{ flex: 1, justifyContent: "center", alignItems: "center", height: 100, margin: 20 }}
            cardElevation={2}
            cardMaxElevation={2}
            cornerRadius={0}
          >
            <Text>Elevation 1</Text>
            <Text>Elevation 2</Text>
            <Text>Elevation 3</Text>
            <Text>Elevation 4</Text>
          </CardView>
```

Having a shadow is nice, but If I can't layout my card contents in the same way on Android and iOS, the component is not very useful.

**Comment by aranda-adapptor** [comment]
Strangely, wrapping the children in a normal RN `View` doesn't work either:

```
          <CardView
            style={{ height: 100, margin: 20 }}
            cardElevation={2}
            cardMaxElevation={2}
            cornerRadius={0}
          >
            <View
              style={{
                flex: 1,
                justifyContent: "center",
                alignItems: "center"
              }}
            >
              <Text>Elevation 1</Text>
              <Text>Elevation 2</Text>
              <Text>Elevation 3</Text>
              <Text>Elevation 4</Text>
            </View>
          </CardView>
```

**Comment by Kishanjvaghela** [comment]
@aranda-adapptor  Thanks for issue. I will look into this and fix by end of the day.

**Comment by Kishanjvaghela** [comment]
@aranda-adapptor I am closing this issue. Please latest version now.

**Comment by aranda-adapptor** [comment]
Thanks for the quick fix!

**Comment by Sundin** [comment]
I'm still having layout problems on Android, the child views are not centered properly using alignItems: "center". Works as it should on iOS.

**Comment by est7** [comment]
@Sundin if u dont send cardElevation value nor send '0',it works?

**Comment by est7** [comment]
@Sundin i have same issues,did u  solve it？

**Comment by Sundin** [comment]
@est7 Unfortunately I didn't find a workaround. I used a normal View component with a borderRadius instead (and thus had to sacrifice the shadow/elevation effect). I didn't try cardElevation: 0 but it should have the same effect if it works like you said.

**Comment by githubdoramon** [comment]
Elevation 0 fixes the issue, but of course removes the shadow. Any updates on this issue?

**Comment by YouCii** [comment]
Is 'height' props must required? I think it would be better like View, which 'height' is adaptive according to the height of its sub-layouts
