### ISSUE TITLE
Build failed while upgrading gradle version

### ISSUE THREAD

**Issue by SrinivasVurrinkala** [Kishanjvaghela/react-native-cardview#37]
**Describe the bug**
When gradle plugin is upgraded to 3.2.1 and build the project it throws exception
A problem occurred configuring project ':react-native-cardview'.
> Could not resolve all artifacts for configuration ':react-native-cardview:classpath'.
   > Could not find com.android.tools.build:gradle:2.2.3.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.jar
     Required by:
         project :react-native-cardview
It seems to be issue with library still using 2.2.3 version. 

**Expected behavior**
Build should be successful while upgrading the gradle plugin.

**Comment by Kishanjvaghela** [comment]
Published to v2.0.3 
https://www.npmjs.com/package/react-native-cardview
Feel free to reopen the issue if not working.
