### ISSUE TITLE
Unable to use cardview

### ISSUE THREAD

**Issue by sakthig** [Kishanjvaghela/react-native-cardview#41]
**Describe the bug**
Not able to use cardview as expected, some kind of shadow is applied to text in cardview. but cardview itself does not have shadow.

**To Reproduce**
This code may help
```
import React from 'react';
import { View, TextInput, Text, Button, Alert, AlertButton } from 'react-native';
import styled from 'styled-components';
import CardView from 'react-native-cardview';

export default class Login extends React.Component {
    static navigationOptions = {
        title: 'Login'
    }
    render() {
        return <View>
            <Panel>
                <Text selectable={false}>Username</Text>
                <Input />
                <Text selectable={false} style={{ marginTop: 20 }}>Password</Text>
                <Input />
                <Button title={"Login"} style={{ marginTop: 20 }} onPress={() => {
                    Alert.alert("Login", "Incorrect Credentials. Try again", ["OK"])
                }} />
            </Panel>
        </View>
    }
}

const Container = styled.View`
    width: 100%;
    height: 100%;
`

const Panel = styled(CardView).attrs(() => ({
    cardElevation: 2
}))`
    top: 20px;
    padding: 20px;
    margin: 0 auto;
    width: 300px;
    height: 600px;
`;

const Input = styled.TextInput`
    padding: 5px;
    margin-top: 5px;
    border: 1px solid #00000077;
    width: 100%;
    height: 40px;
`;
```

**Expected behavior**
Shadow should be applied to cardview not elements inside it.\

**Screenshots**
![Simulator Screen Shot - iPhone X - 2019-03-16 at 10 46 30](https://user-images.githubusercontent.com/101381/54471053-c7aca800-47d8-11e9-8fcf-7aa54264920b.png)

**Smartphone (please complete the following information):**
 - Device: iPhoneX simulator
 - OS: iOS12.1

**Comment by Kishanjvaghela** [comment]
Use background to cardview.
`style={{
              backgroundColor: 'white'
            }}`

Follow example https://github.com/Kishanjvaghela/react-native-cardview/blob/master/example/Example1.js#L79
