### ISSUE TITLE
how to use custom shadow color

### ISSUE THREAD

**Issue by KingAmo** [Kishanjvaghela/react-native-cardview#46]
i want to change the color of the  shadow，any solution ?

**Comment by marlti7** [comment]
same problem

**Comment by kristoff2016** [comment]
Any update?

**Comment by club9822** [comment]
https://github.com/879479119/react-native-shadow ?

**Comment by RNdeveloper0305** [comment]
I know how to customize shadow color and border in this module?
Please help me.
