### ISSUE TITLE
Not working with react-native 0.60 in Android, AndroidX

### ISSUE THREAD

**Issue by jibraniqbal666** [Kishanjvaghela/react-native-cardview#47]
Not working with react-native 0.60 in Android, Please include AndroidX dependencies, because this does not include support schema.

**Comment by Thanhcao86** [comment]
in androidX the lib com.android.support:cardview-v7 try edit become: androidx.cardview:cardview:1.0.0

**Comment by Kishanjvaghela** [comment]
Published to v2.0.3 
https://www.npmjs.com/package/react-native-cardview
Feel free to reopen the issue if not working.
