### ISSUE TITLE
Release Build failed 

### ISSUE THREAD

**Issue by basha777** [Kishanjvaghela/react-native-cardview#49]
Execution failed for task ':react-native-cardview:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/admin/Documents/GitHub/graphqlLat/Upgrade/naberly-experts-app/node_modules/react-native-cardview/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/admin/Documents/GitHub/graphqlLat/Upgrade/naberly-experts-app/node_modules/react-native-cardview/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/admin/Documents/GitHub/graphqlLat/Upgrade/naberly-experts-app/node_modules/react-native-cardview/android/build/intermediates/res/merged/release/values/values.xml:2738: error: resource android:attr/fontVariationSettings not found.
  /Users/admin/Documents/GitHub/graphqlLat/Upgrade/naberly-experts-app/node_modules/react-native-cardview/android/build/intermediates/res/merged/release/values/values.xml:2739: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Smartphone (please complete the following information):**
- React Native 0.59.9
 - OS: macOs mojave 10.14.5

**Comment by Kishanjvaghela** [comment]
Published to v2.0.3 
https://www.npmjs.com/package/react-native-cardview
Feel free to reopen the issue if not working.

**Comment by mattop1709** [comment]
Alright thanks! will check it out
