### ISSUE TITLE
Trying to remove a view index above child count- Android

### ISSUE THREAD

**Issue by hmachaharywork** [Kishanjvaghela/react-native-cardview#5]
I get this error whenever I try to remove and item which is rendered from an array of objects inside a  CardView. I got this error only in android.

**Comment by Kishanjvaghela** [comment]
@hmachaharywork Can you share your code here?

**Comment by hmachaharywork** [comment]
Sorry, I was away so couldn't reply. I cannot share the original code, but I have created a test code. I was using RN 0.38.1 in my project. Thought it was due to the version of react native but after testing the below code with RN 0.44.2, found out that its not the version. Solved some problem from [here](https://stackoverflow.com/questions/41819759/trying-to-remove-a-view-index-above-child-count-error) . 
But couln't solve the problem below.

`import React, { Component } from 'react';
import CardView from 'react-native-cardview';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
} from 'react-native';


export default class testing extends Component {

  constructor() {
    super();
    this.state = {
      data: [
        {id: 1, addr: "Hello"},
        {id: 2,  addr: "Hi, Nice to meet you"},
        {id: 3,  addr: "Hello, Nice to meet you too."},
        {id: 4,  addr: "How are you?"}
      ]
    }
  }

   deleteData(id) {
    let filteredData = this.state.data.filter((item) => {
      return item.id !== id;
    })
    this.setState({
      data: filteredData
    })
  }

  renderData(data) {
    return data.map((item) => {
      return(
        <View key={item.id} style={{flexDirection: 'row', paddingTop: 5}}>
          <View style={{flex: .6, paddingLeft: 10}}>
            <Text>{item.addr}</Text>
          </View>
          <TouchableOpacity
            style={{flex: .2}}
            onPress={() => this.deleteData(item.id)}
          >
            <Text>Delete</Text>
          </TouchableOpacity>
        </View>
      )
    });
  }

  render() {
    const {data} = this.state;
    return (
      <View style={styles.container}>
        <CardView
          style={{paddingBottom: 20}}
          cardElevation={2}
          cardMaxElevation={2}
          cornerRadius={5}
        >
          <View style={{width: 300}}>
            <View style={{padding: 5,borderBottomColor: '#e3e3e3', borderBottomWidth: 1,}}>
              <Text style={{fontSize: 16}}>User Information</Text>
            </View>
            <View>
              {
                this.renderData(data)
              }
            </View>
          </View>
        </CardView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});

AppRegistry.registerComponent('testing', () => testing);`

**Comment by hmachaharywork** [comment]
@Kishanjvaghela have you found the solution for the above issue?

**Comment by Kishanjvaghela** [comment]
@hmachaharywork 
I have fixed your issue. Please use the latest version now 
###  `"react-native-cardview": "^1.0.4"`
Here is your demo output 

![peek 2017-06-02 16-18](https://cloud.githubusercontent.com/assets/11232063/26723090/6fb78928-47b0-11e7-84ce-5bcee8b4ed21.gif)

**Comment by Kishanjvaghela** [comment]
@hmachaharywork You can find example [here](https://github.com/Kishanjvaghela/react-native-cardview-example)

**Comment by hmachaharywork** [comment]
@Kishanjvaghela Thanks for the quick fix. Appreciate your hard work.
