### ISSUE TITLE
i am put index.d.ts to project of react-native root directory, but notice is not found file of  type declare

### ISSUE THREAD

**Issue by huaiguoguo** [Kishanjvaghela/react-native-cardview#66]
**Describe the bug**

**To Reproduce**

i am install with "yarn add react-native-cardview"
i am cofigure the react-native-cardview completely in accordance with official document
i am mkdir directory typing in project of react-native and put official index.d.ts in it;

**Expected behavior**

but visual code is still notice not found type declare file;

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]  android api 28
 - OS: [e.g. iOS8.1] android api 28
 - Version [e.g. 22] latest version  of react-native

**Additional context**

**Comment by Kishanjvaghela** [comment]
Can you please create PR? I will look into it?

**Comment by huaiguoguo** [comment]
is ok, 
beause i configured android/setings.gradle, android/app/build.gradle, the above error occurs
latest version for react-native is does't need to configured
