### ISSUE TITLE
Invariant Violation: Text strings must berendered within a <Text> component.

### ISSUE THREAD

**Issue by W-Qing** [Kishanjvaghela/react-native-cardview#69]
**Describe the bug**
Invariant Violation: Text strings must berendered within a <Text> component.

      This error is located at:

      in RCTView (at ModuleCard.js:61)

      in RNCardView (at CardView.android.js:46)in CardView (at ModuleCard.js:51)in RCTView (at ModuleCard.js:50)

      in ModuleCard (at TaskSelector.js:28)in RCTView (at TaskSelector.js:23)in TaskSelector (at SceneView.tsx:98)in StaticContainer

      in StaticContainer (at SceneView.tsx:89)in EnsureSingleNavigator (atSceneView.tsx:88)

      in SceneView (at useDescriptors.tsx:125)in RCTView (at CardContainer.tsx:190)in RCTView (at CardContainer.tsx:189)in RCTView (at Card.tsx:515)in RCTView (at

      createAnimatedComponent.js:151)

      in AnimatedComponent (at Card.tsx:498)in PanGestureHandler (at Card.tsx:491)in RCTView (at

      createAnimatedComponent.js:151)

      in AnimatedComponent (at Card.tsx:487)
...
**To Reproduce**

The steps are the same as the demo in the documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/30466018/82033905-fde10280-96cf-11ea-9738-53da7c93992c.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. MI6]
 - OS: [e.g. MIUI 11]
 - Version [latest]

**Comment by Kishanjvaghela** [comment]
Try to run the example in the demo. It should work. It will be easy to identify if you provide your code. But it looks like its some minor problem. StackOverflow it better ways to solve
